modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/rosevcook/fermion/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "fermion"
    version = "1.1.0"
    displayName = "Fermion"
    logoFile = "logo.png"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/fermion"
    authors = "Rose"
    description = '''Fermion is a mod that allows you to hide items from creative mode tabs, customize tab icons + many new item tooltips. the perfect vanilla+ mod and modpack making tool.'''

[[dependencies.fermion]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.fermion]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"
